### ISSUE TITLE
No plugin export in ESM

### ISSUE THREAD

**Issue by selfagency** [fastify/fastify-auth#178] opened 2022-11-29 14:28 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.10.2

### Plugin version

4.2.0

### Node.js version

18.12.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.1

### Description

The result of these exports...

```js
module.exports = fp(fastifyAuth, {
  fastify: '4.x',
  name: '@fastify/auth'
})
module.exports.default = fastifyAuth
module.exports.fastifyAuth = fastifyAuth
```

...when imported into ESM is that you wind up with two instances of `fastifyAuth` and no plugin, whereas `default` is, as so named, the default import. If you try doing `import * as fastifyAuthPlugin`, you still wind up with just the `default` and `fastifyAuth` properties.

For compatibility with modern JavaScript it should really be:

```js
module.exports.default = fp(fastifyAuth, {
  fastify: '4.x',
  name: '@fastify/auth'
})
module.exports.fastifyAuth = fastifyAuth
```

### Steps to Reproduce

See above.

### Expected Behavior

For the plugin to be the default export.

**Comment by Uzlopak** [comment] 2022-11-29 14:34
Please provide a repo, which can be cloned and investigated.

**Comment by selfagency** [comment] 2022-11-29 14:35
i realized i missed `after()` so now the second half of the ticket is irrelevant

**Comment by Uzlopak** [comment] 2022-11-29 14:39
It is not reproducable, if you dont provide a repository as mvce, as we actually tested this see https://github.com/fastify/fastify/issues/4349

So please provide a repository to investigate it further.

**Comment by Eomm** [comment] 2022-11-30 18:08
Is v4.2.0 solving this issue?

**Comment by climba03003** [comment] 2022-11-30 18:35
I am closing this issue because the author do not provide a clear step to reproduce the problem.

```mjs
import defaultImport, { fastifyAuth as namedImport } from '@fastify/auth'
console.log(defaultImport)
console.log(namedImport)
```

My advice would be double check the version you install using `npm list @fastify/auth`.
or if you are using bundler, please file an issue in their repo. We are strictly follow how [`Node Module System` behavior](https://nodejs.org/api/esm.html#commonjs-namespaces) and provide the correct `export` syntax.

**Closed by climba03003** 2022-11-30 18:35 UTC
