### ISSUE TITLE
Type definitions as defined in the route schema get removed when using fastify auth

### ISSUE THREAD

**Issue by mapokapo** [fastify/fastify-auth#222] opened 2024-02-11 17:50 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.0.0

### Plugin version

4.5.0

### Node.js version

18.18.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Fedora 39

### Description

When you define a body schema in the fastify route options, you get Typescript type completion in the handler function.
However, adding the fastify auth function to the `onRequest` or `preHandler` hook removes these definitions, and makes body of type `unknown`.

### Steps to Reproduce

Take the following route for example:
```ts
fastify.route({
    method: "POST",
    url: "/",
    schema: {
      body: CreateTodo,
      response: {
        201: ReturnTodo,
      },
    },
    onRequest: fastify.auth([fastify.verifyJWT]),
    handler: async ({ body }, reply) => {
      const result = await fastify.prisma.todo.create({ data: body }); // error here: "body is of type `unknown`"
      const todo = {
        ...result,
        createdAt: result.createdAt.toISOString(),
        updatedAt: result.updatedAt.toISOString(),
      };

      reply.code(201);
      return todo;
    },
  });
```
However, when we remove the `onRequest` hook, the error disappears.

### Expected Behavior

The type definitions from the schema should carry on through the hook where the fastify auth function is used, and should apply to the actual handler function.

**Comment by climba03003** [comment] 2024-02-11 18:12
Duplicate of #207

**Closed by climba03003** 2024-02-11 18:12 UTC

**Comment by climba03003** [comment] 2024-02-11 18:14
You may try the `master` branch here to see if the problem solved.
